server:
  port: 8000
  servlet:
    context-path: /@project.artifactId@
spring:
  application:
    name: @project.artifactId@
    version: @project.version@
    fullname: @project.name@
  mvc:
    dispatch-options-request: true
logging:
  level:
    org.springframework: ERROR
    com.maryanto.dimas.example: ${LOG_LEVEL:DEBUG}
  file: ${LOG_LOCATION:${spring.application.name}.log}
